import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <ul className="flex space-x-4">
            <li className="menu-item">
              <Link
                href="/backtest-sessions"
                className="text-white hover:text-gray-400"
              >
                Backtest Sessions
              </Link>
            </li>
            <li className="menu-item">
              <Link
                href="/backtest-results"
                className="text-white hover:text-gray-400"
              >
                Backtest Results
              </Link>
            </li>
            <li className="menu-item">
              <Link
                href="/strategies"
                className="text-white hover:text-gray-400"
              >
                Strategies
              </Link>
            </li>
            <li className="menu-item">
              <Link
                href="/timeframe-sets"
                className="text-white hover:text-gray-400"
              >
                Timeframe Sets
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
